language: ruby
rvm:
- 2.3.1
sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y texlive-lang-cjk texlive-fonts-recommended texlive-latex-extra
  texlive-fonts-extra latex-xcolor --no-install-recommends
script:
- bundle exec rake all 0<&-
after_success:
- wget https://kindlegen.s3.amazonaws.com/kindlegen_linux_2.6_i386_v2_9.tar.gz -O - | tar xzvf - kindlegen
- ./kindlegen C91.epub -c2 -verbose -o C91.mobi
deploy:
  provider: releases
  api_key:
    secure: BTV95ZMcs6WMpc0P2W7KnMsXwcHkky+G+m9lnigHefAJ06RNmHbZTBYd6heiW7U6UsOkU5IVVjCxSNVMojHDxgIIfIaIOYQRCzmd7u0o/HIt9TcuyE/1NSgGgg9J+JzW6UzGA1WbosoO213Q4xSAIw9mBK5B3AClwdR4BIwiJ5r17TOglRNHmKEhg7C24e7ZaHRcqtSdBAJZ1jfV5pfTaAA684MwHz1XEnSBUvv4JZsjd/moY9j3zpn1n5oZvfc1QPP7Zo9aN3edZob9N8Ct8FoJ9+LVenCh52T5Htfqcxp88geB9/ohfoOlx5j3hmOflQNqtv4aBUtQarymi8hZ+tjlAFtf9SakkSznuy5fTgO3Wj7svniXdez5sVb4TEROS8+FAqNlhGDSIrIdZes9DRHih4JK2gZ7stphiuyJ4hIXZEofsnqW0onDmVqrGzTGa504YfQ6H1pFHCB3tEhooBMiEJaqHwlva82MWcex6Z4L/UIq8bIE/lp7jL9j4GmQpkZVIDW1jNFSKCvwXq/F/pcuzVFhP/15i/dPjLb1hljP7XwUfKceAHin/3tcFkUFMz+VdGOA/EGFCA/Zp8Poiv2iBtNlo9AmPr/y/sgew3IqjhiFeHQZ6828dSx7JiusBzfRMcasI0X+CE1V2UauzMuGBAn8SLr1RxCrc3zQ/OY=
  file:
  - C91.pdf
  - C91.epub
  - C91.mobi
  skip_cleanup: true
  on:
    tags: true
    repo: hakatashi/SunPro-C91
notifications:
  slack:
    secure: xDBzO6kygJU/d3yiV9CsM3StlrjlepeT1hCyFud5Xs8fQ5kqbOLstVGU8Vk70VPUcqgaCuTtsVNWgNSyOp34bcpwjV0XNy4/s3ANk34mZye6i5a8Ih5TkC9AMHJMJGrM9mIIEYQbaL+NOe42kv6SWiWjD81KT87ZXktSlek2mUhITyvG7XnG/s0TmsAgyuSEYIEGPo/R0+fkLdRZk/MIvoDbt1TNa0cTlK8S8UnRaHibLTFR2+jqe0iImlKvWwYvWsAvgqaeeXi4qz+8uMjz2cRAhq2an7/914mvW9Zk4yZor0+zpXPfQMSfCPPYCF0kDJn4Td+kwnHMyjqjDRfGgamXsoWiyIPdOwpXDnlwvOMN1jp5Rnxqxn/Pdt1nnGlpDbBCEISbK1C+tQHxfFzsfVLC9KwBf/Jkmqo34AXDglktaeeHpmSBnMIVkp0IbXdDNtX9bbo2BUNIQiVIN9xaqeoS3J7sGab+QJuxvmNTWlpZ4aoF9sPKK/vocYNvLOaduVvgtVqh1IdGUCqyjwpF/dSIehBROR0sc/qSO5SmhVuzg09qKEfjJfSzH6oVr1Mt/T03g2ZSk7/jIVMa6bPNG4SG2M9jP/xUAwMCILQB8AP2Q1dJSDs9cBPnGg3F03SpY9D+QfG60pO47SRPfpZOyhVTZ4gtXg9FmKKKieB77A4=
